name: CI

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - uses: ramsey/composer-install@v3

      - name: Check coding style
        run: composer cs-check

      - name: Run unit tests
        run: composer test:unit
